### ISSUE TITLE
Any plan on iOS?

### ISSUE THREAD

**Issue by zzeitt** [pint-sized/taskbridge#1]
I've been looking for a “bridge” between iPhone's Reminder and Emacs's OrgMode (or any other Linux based todo-app), your project sounds something like that. So do you have any plan on developing an iOS version of it?

**Comment by pint-sized** [comment]
Unfortunately, iOS is too locked down for something like this to work. TaskBridge relies on AppleScript actions to get and set data in Apple Notes & Reminders, so the sync itself must happen on macOS.

**Comment by pint-sized** [comment]
Closing as not planned
